### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by RectangleEquals** [max-arias/poeTradeIgnoreList#2]
It is now (3.11) Harvest league, and this extension stopped filtering out blacklisted sellers as of (3.10) Delirium league.
Currently running the latest Chrome, Version 83.0.4103.97 (Official Build) (64-bit).
Haven't looked into your code or anything, but perhaps poe.trade changed around and/or renamed some html elements? idk

**Comment by max-arias** [comment]
Hey, I haven't been keeping this repo up to date (I usually just use the path of exile shop now anyways), but I'll take a look this weekend and see if I can fix the issue.

Thanks for the report!

**Comment by max-arias** [comment]
@RectangleEquals Should be working now. New version published. Thanks for the report.
